### ISSUE TITLE
PipelineException Unable to Verify the Server is Elasticsearch

### ISSUE THREAD

**Issue by tylerj-aft** [serilog-contrib/serilog-sinks-elasticsearch#481]
- [X] Bug (or maybe configuration error)
- [ ] New Feature

**Serilog.AspNetCore 6.0.1"**
**Serilog.Enrichers.Environment 2.2.0**
**Serilog.Sinks.Debug 2.0.0**
**Serilog.Sinks.Elasticsearch 8.4.1**

**Running Elasticsearch 7.10.2 in a docker.**
I've tried 7.17.7 and 8.5.0 with the same result.

**Target framework .NET 6**
Debugging using a docker-compose.dcproj project in one docker network talking to the container in another docker network. Kibana comes up and is able to write sample data to the running instance of ES.

GET localhost:9200
```
{
  "name" : "6a75576567de",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "UKfelxzOTMK-e_jWI0OYtg",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Behavior**
SelfLog to console indicates an unsuccessful product check.
```
2022-11-13T23:29:20.4707445Z Failed to create the template. Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:9200)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
```

Code being used in .NET 6 web app with a simple call to log an information in the index page Get method:
```
    private static void Main(string[] args)
    {
        Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));
        var builder = WebApplication.CreateBuilder(args);
        try
        {
            if (builder.Environment.IsDevelopment())
            {
                ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            }

            var options = new ElasticsearchSinkOptions(new Uri(builder.Configuration["ElasticSearch:Url"]))
            {
                AutoRegisterTemplate = true,
                AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                IndexFormat = $"{builder.Configuration["App:Name"].ToLower().Replace(".", "-")}-logs-{builder.Configuration["App:Environment"].ToLower().Replace(".", "-")}-{DateTime.UtcNow:yyyy-MM}"
            };
            //var provided = options.ModifyConnectionSettings;
            //options.ModifyConnectionSettings = configuration =>
            //{
            //    configuration.EnableApiVersioningHeader();
            //    configuration = provided?.Invoke(configuration) ?? configuration;
            //    return configuration;
            //};

            var logger = new LoggerConfiguration()
              .ReadFrom.Configuration(builder.Configuration)
              .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
              .Enrich.FromLogContext()
              .Enrich.WithMachineName()
              .Enrich.WithEnvironmentName()
              .WriteTo.Debug()
              .WriteTo.Console()
              .WriteTo.Elasticsearch(options)
              .CreateLogger();
            builder.Logging.ClearProviders();
            builder.Logging.AddSerilog(logger);

            // Add services to the container.
            builder.Services.AddRazorPages();

            var app = builder.Build();

            Log.Information("Starting host.");

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.MapRazorPages();

            app.Run();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Host failure.");
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }


    private static void LogFailure(LogEvent logEvent)
    {
        Console.WriteLine(logEvent.ToString());
    }
```

App settings:
```
{
  "App": {
    "Name": "LoanFlowWeb",
    "Environment": "LocalDev",
    "SelfUrl": "https://localhost:44714"
  },
  "AllowedHosts": "*",
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Warning"
      }
    }
  },
  "ElasticSearch": {
    "Url": "http://localhost:9200"
  }
}
```

My docker-compose is (ignore secrets--they're just for local dev only):

```
version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - platform-network
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
    ports: 
      - 5601:5601
    networks:
      - platform-network
      
volumes:
  esdata:
    driver: local
 
networks:
  platform-network:
    external: true
    driver: bridge

```

**Expected: writing data to an index on ES**

I've not been able to get this work with a variety of changes, including adding the latest Elasticsearch.Net package and using the commented code to call EnableApiVersionHeader.
